site_name: Vulcan
nav:
  - Home: index.md
  - Use Cases:
    - Continuous Scanning: continuous-scanning.md
    - Asset Auto-Discovery: asset-auto-discovery.md
    - Security Checks in CI/CD: security-checks-in-ci-cd.md
    - Security Metrics: security-metrics.md
  - Architecture: architecture.md
  - Repositories: repositories.md
theme:
  name: material
  logo: img/logo.svg
  favicon: img/logo.png
  features:
    - navigation.tracking
    - navigation.sections
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/adevinta/vulcan-docs
markdown_extensions:
    - attr_list
    - toc:
        permalink: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
